table gdm_predictions_secondTrimester
	lineageTag: 29bae4b2-29d0-4816-a4b6-8ef441c57034

	column case_id
		dataType: int64
		formatString: 0
		lineageTag: 8089d63c-3be7-4b05-a25e-f1c94eef6e0a
		summarizeBy: none
		sourceColumn: case_id

		annotation SummarizationSetBy = Automatic

	column GDM
		dataType: int64
		formatString: 0
		lineageTag: 9ac7a802-eab7-4b04-a9b3-e17a174c6779
		summarizeBy: sum
		sourceColumn: GDM

		annotation SummarizationSetBy = Automatic

	column predicted_GDM
		dataType: int64
		formatString: 0
		lineageTag: 9e303d96-06d1-42f6-90b4-b33a24869e6d
		summarizeBy: sum
		sourceColumn: predicted_GDM

		annotation SummarizationSetBy = Automatic

	partition gdm_predictions_secondTrimester = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\anuva\gdm_predictions_secondTrimester.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Use First Row as Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Change Type" = Table.TransformColumnTypes(#"Use First Row as Headers",{{"case_id", Int64.Type}, {"GDM", Int64.Type}, {"predicted_GDM", Int64.Type}})
				in
				    #"Change Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

