table 'public demographics'
	lineageTag: b7c3e183-7f3e-464d-8abc-4a42957eed1b

	measure TotalDisPatients = DISTINCTCOUNT('public demographics'[case_id])
		formatString: 0
		lineageTag: 694974b2-425a-4c09-8fab-05c2fffe179e

	measure Average_Age = AVERAGE('public demographics'[age_years_old])
		lineageTag: a886a239-a438-44da-b8b5-7db5713a26f1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Max_Age = MAX('public demographics'[age_years_old])
		formatString: 0
		lineageTag: 1972dd85-2728-4240-abb0-5a248b244fe1

	measure Min_Age = MIN('public demographics'[age_years_old])
		formatString: 0
		lineageTag: 0115405a-0cc7-477a-8306-2983698ddcd9

	measure 'Total cases' = COUNT('public demographics'[case_id])
		formatString: 0
		lineageTag: 8e229760-b136-4b99-a137-2c57434e4df0

	column case_id
		dataType: int64
		formatString: 0
		lineageTag: c64ce869-a470-436a-a3c1-d5aff03a637e
		summarizeBy: none
		sourceColumn: case_id

		annotation SummarizationSetBy = Automatic

	column age_years_old
		dataType: int64
		formatString: 0
		lineageTag: 8e34e2bc-cda2-492a-8d4b-b509a6884f3e
		summarizeBy: sum
		sourceColumn: age_years_old

		annotation SummarizationSetBy = Automatic

	column color_ethnicity
		dataType: string
		lineageTag: b258ce4e-ec65-4c19-ab24-c08bdcf9f75d
		summarizeBy: none
		sourceColumn: color_ethnicity

		annotation SummarizationSetBy = Automatic

	column AgeGroup = ```
			
			SWITCH(
			    TRUE(),
			    'public demographics'[age_years_old] >= 15 && 'public demographics'[age_years_old] <= 17, "15-17",
			    'public demographics'[age_years_old] >= 18 && 'public demographics'[age_years_old] <= 25, "18-25",
			    'public demographics'[age_years_old] >= 26 && 'public demographics'[age_years_old] <= 35, "26-35",
			    'public demographics'[age_years_old] >= 36 && 'public demographics'[age_years_old] <= 45, "36-45",
			   
			    "Unknown"
			)
			
			```
		lineageTag: df9b4a2d-4991-4e99-af73-1fc836f078d4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Age_Group =
			
			SWITCH (
			    TRUE (),
			    'public demographics'[age_years_old] < 20, "Under 20",
			    'public demographics'[age_years_old] >= 20 && 'public demographics'[age_years_old] < 30, "20-29",
			    'public demographics'[age_years_old] >= 30 && 'public demographics'[age_years_old] < 40, "30-39",
			    'public demographics'[age_years_old] >= 40, "40 and above"
			)
		lineageTag: 12ac045f-f38c-48a6-b566-2792bfe307b4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'public demographics' = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("localhost:5432", "Project_MH"),
				    public_demographics = Source{[Schema="public",Item="demographics"]}[Data]
				in
				    public_demographics

	annotation PBI_ResultType = Table

